apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: clever-home
  name: clever-home-viewer
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["get", "list", "watch"] 
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: clever-home
  name: clever-home-admin
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-pods-viewer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-devops-admin
rules:
- apiGroups: [""]
  resources: [""]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]