apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: hostpathconstraint
spec:
  crd:
    spec:
      names:
        kind: HostPathConstraint
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package hostpathconstraint

        ir := input.request

        violation[{"msg": msg}] {
          ir.namespace == ["audit-zone"]
          ir.object.spec.volumes[0].hostPath.path == ""
          msg := "host path is not allowed!"
        }